### ISSUE TITLE
[Automasher] Vanilla automasher not fast enough

### ISSUE THREAD

**Issue by AntyMew** [danielah05/WebfishingMods#1]
Please undeprecate this mod, as-is I am unable to catch any fish with barriers above 1.5k despite having max fishing power (ex. alpha creature)

The vanilla game seems to attempt to compromise accessibility with balance, there's still a case to be made for an unabashedly unbalanced alternative

**Comment by kittibyte** [comment]
mod has been replaced with "AutoclickerTweaks", it lets u adjust the autoclicker to be any speed, i recommend downloading this one instead

https://thunderstore.io/c/webfishing/p/danielah05/AutoclickerTweaks/
